# Site settings
title: 我的个人博客
description: > # this means to ignore newlines until "baseurl:"
  HELLO WORLD!
timezone: Asia/Shanghai
copyright: 2022

# social links
github_username:  uwyc
cnblogs_username: uwyc
rss: rss

# Build settings
markdown: kramdown
kramdown:
  input: GFM
theme: minima
plugins:
  - jekyll-feed
sass:
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - README.md
  - changelog.md
  - files/
  - others/

# Friend links
friends:
  - title: 代码咖啡 - 简书
    href:  https://www.jianshu.com/u/9b87ba5fc959
    img:   https://upload.jianshu.io/users/upload_avatars/291600/4c689e155899.jpg
  - title: 程序员叨叨叨
    href:  https://wjnovember.github.io
    img:   https://wjnovember.github.io/images/avatar_32x32.png
  - title: 爱吃炸鸡翅 - 博客园
    href: https://www.cnblogs.com/izumiy/
    img: https://pic.cnblogs.com/face/1181389/20170612145026.png
